- name: First boot configuration for Kali Linux
  hosts: localhost
  become: yes
  vars_files:
    - secrets.yml
  roles:
    - { role: common,        tags: [common] }
    - { role: docker,        tags: [docker] }
    - { role: ssh_hardening, tags: [ssh] }
    - { role: firewall,      tags: [firewall] }
    - { role: cleanup,       tags: [cleanup] }
    - { role: dockge,        tags: [dockge] }
    - { role: kismet,        tags: [kismet] }
    - { role: angryoxide,    tags: [angryoxide] }
    - { role: aistocot,      tags: [aistocot] }