- name: Add Kismet APT repository
  deb822_repository:
    name: kismet
    types: deb
    uris: https://www.kismetwireless.net/repos/apt/git/kali
    suites: kali
    components: main
    architectures: amd64
    signed_by: https://www.kismetwireless.net/repos/kismet-release.gpg.key

- name: Update APT cache for Kismet
  apt:
    update_cache: yes

- name: Install Kismet git package for Kali Linux
  apt:
    name: kismet
    state: present

- name: Remove obsolete Kismet metapackage when using git version
  apt:
    name: kismet-capture-common
    state: absent
    purge: yes

- name: Ensure 'kali' is in the kismet group
  user:
    name: kali
    groups: kismet
    append: yes

- name: Create Kismet log directory
  file:
    path: /home/kali/kismet
    state: directory
    owner: kali
    group: kali
    mode: '0755'

- name: Create Kismet user directory
  file:
    path: /home/kali/.kismet
    state: directory
    owner: kali
    group: kali
    mode: '0755'

- name: Deploy kismet_site.conf
  copy:
    dest: /etc/kismet/kismet_site.conf
    content: |
      log_types=kismet,pcapng,pcapppi
      log_prefix=/home/kali/kismet
      gps=gpsd:host=localhost,port=2947
    owner: root
    group: root
    mode: '0644'

- name: Allow Kismet Web UI through UFW
  ufw:
    rule: allow
    port: 2501

# Change the username/password for the web interface here
- name: Deploy kismet_httpd.conf
  copy:
    dest: /home/kali/.kismet/kismet_httpd.conf
    content: |
      httpd_password=kali
      httpd_username=kali
    owner: kali
    group: kismet
    mode: '0644'

- name: Create Kismet service directory for override.conf file
  become: yes
  file:
    path: /etc/systemd/system/kismet.service.d/
    state: directory
    mode: '0755'

# The user/group typically gets overwritten back to root/root on package upgrades
- name: Create user/group override for the Kismet service
  copy:
    dest: /etc/systemd/system/kismet.service.d/override.conf
    content: |
      [Service]
      User=kali
      Group=kismet

- name: Reload systemd to pick up Kismet service
  systemd:
    daemon_reload: yes

- name: Enable and start Kismet service
  systemd:
    name: kismet.service
    enabled: yes
    state: started
