- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: kali
    group: kali
    mode: '0755'
  loop:
    - /opt/stacks
    - /opt/stacks/filebrowser
    - /opt/stacks/filebrowser/data
    - /opt/stacks/filebrowser/config

- name: Write docker-compose.yml file
  copy:
    dest: /opt/stacks/filebrowser/docker-compose.yml
    content: |
      services:
        filebrowser:
          image: filebrowser/filebrowser:latest
          container_name: filebrowser
          user: 1000:1000
          environment:
            - FB_DATABASE=/config/filebrowser.db
            - FB_PORT=80
            - FB_ROOT=/data
          restart: unless-stopped
          ports:
            - 8282:80
          volumes:
            - ./data:/data
            - ./config:/config
            - /home/kali/kismet:/data/kismet

- name: Allow web interface through UFW
  ufw:
    rule: allow
    port: 8282