- name: Set static IP for eth0 using nmcli
  community.general.nmcli:
    conn_name: eth0
    ifname: eth0
    type: ethernet
    ip4: 192.168.1.25/24
    gw4: 192.168.1.1
    state: present
    autoconnect: yes