- name: Update APT cache
  apt:
    update_cache: yes

- name: Install package
  apt:
    name: chrony
    state: latest

- name: Reload systemd to pick up new service
  systemd:
    daemon_reload: yes

- name: Enable service to start at boot
  systemd:
    name: chrony.service
    enabled: yes

- name: Start service
  systemd:
    name: chrony.service
    state: started