- name: Enable SSH password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    backrefs: yes

- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin no'
    backrefs: yes

- name: Restart SSH if config changed
  service:
    name: ssh
    state: restarted
    enabled: yes
  notify: Restart SSH