- name: Allow UDP ports for AIStoCOT containers
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: udp
  loop:
    - { port: 6969 }
    - { port: 2233 }
    - { port: 2222 }

- name: Download AIStoCOT archive
  get_url:
    url: https://github.com/hobobandy/aistocot/archive/refs/heads/main.zip
    dest: /tmp/aistocot.zip
    mode: '0644'

- name: Extract AIStoCOT to /opt/stacks/aistocot
  unarchive:
    src: /tmp/aistocot.zip
    dest: /opt/stacks
    remote_src: yes

- name: Rename AIStoCOT extracted directory
  command: mv /opt/stacks/aistocot-main /opt/stacks/aistocot

- name: Clean up AIStoCOT archive
  file:
    path: /tmp/aistocot.zip
    state: absent