- name: Create Dockge stacks directory (if it doesn't exist)
  file:
    path: "/opt/stacks"
    state: directory
    owner: kali
    group: kali
    mode: '0755'

- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/hobobandy/aistocot.git'
    dest: /opt/stacks/aistocot
  become: yes
  become_user: kali

- name: Allow UDP ports for containers
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: udp
  loop:
    - { port: 6969 }
    - { port: 2233 }
    - { port: 2222 }